name: Release

permissions:
  contents: write

on:
  push:
    tags: [ "v*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-latest
            features: astro-dnssd
          - os: ubuntu-24.04
            features: avahi
          - os: ubuntu-24.04-arm
            features: avahi

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v6.0.2
    - if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y libavahi-compat-libdnssd-dev libdbus-1-dev pkg-config
    - run: rustup toolchain install 1.95 && rustup default 1.95
    - run: cargo build --verbose --release --no-default-features --features ${{ matrix.features }}
    - uses: actions/upload-artifact@v7.0.1
      with:
        name: daikin-matter_${{ matrix.os }}
        path: target/release/daikin-matter

  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v8.0.1
    - run: ls -R
    - run: |
        chmod +x daikin-matter_macos-latest/daikin-matter
        tar zcvf daikin-matter_macos-latest.tar.gz daikin-matter_macos-latest
        chmod +x daikin-matter_ubuntu-24.04/daikin-matter
        tar zcvf daikin-matter_ubuntu-24.04.tar.gz daikin-matter_ubuntu-24.04
        chmod +x daikin-matter_ubuntu-24.04-arm/daikin-matter
        tar zcvf daikin-matter_ubuntu-24.04-arm.tar.gz daikin-matter_ubuntu-24.04-arm
    - uses: softprops/action-gh-release@v3.0.0
      with:
        files: |
          daikin-matter_macos-latest.tar.gz
          daikin-matter_ubuntu-24.04.tar.gz
          daikin-matter_ubuntu-24.04-arm.tar.gz
